services:
  a:
    build: .
    # network_mode: host
    ports:
      - "2222:22"
  b:
    build: .
    # network_mode: host
    ports:
      - "2223:22"
  # client:
  #   build:
  #     dockerfile: Dockerfile.client
